# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x07\x65xample\"\x1e\n\x0e\x45xampleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0c\x45xampleReply\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x07\x45xample\x12?\n\rExampleMethod\x12\x17.example.ExampleRequest\x1a\x15.example.ExampleReplyB\x0e\xaa\x02\x0bGrpcExampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GrpcExample'
  _globals['_EXAMPLEREQUEST']._serialized_start=24
  _globals['_EXAMPLEREQUEST']._serialized_end=54
  _globals['_EXAMPLEREPLY']._serialized_start=56
  _globals['_EXAMPLEREPLY']._serialized_end=87
  _globals['_EXAMPLE']._serialized_start=89
  _globals['_EXAMPLE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
